### ISSUE TITLE
[补充内容]关于QMCv2 RC4加密

### ISSUE THREAD

**Issue by nukemiko** [parakeet-rs/docs#7]
1. 目前我发现的所有使用 QMCv2 RC4 加密的文件，其密钥长度都是512，而不是[相关页面](https://docs.parakeet.jixun.dev/docs/tencent/qmc2/rc4)上写的256
2. 建议在页面上提示读者：此为标准 RC4 算法的私有增强版本，其 S-box 会周期性地重置

**Comment by jixunmoe** [comment]
有没有兴趣提交 pr

我有可能在新年之后才会进行代码提交。

**Comment by jixunmoe** [comment]
如果有兴趣可以审阅下 #8 的信息。姑且写了个初稿。
